"""Public application ports consumed by runtime code."""
from __future__ import annotations

from typing import Any, Mapping, Protocol, runtime_checkable

from memory.contracts import (ApproveSkillCandidate, AssembleCase,
                              CompleteExperienceUsage, CompleteSkillUsage,
                              CreateMemoryRelation,
                              CreatePersonalProjection, CreatePersonalRecord, ForgetMemory,
                              FormatProjectedContext, IngestPersonalKnowledge, MemoryEvent,
                              IngestGroupFact,
                              IngestBotFactObservations,
                              IngestBotReflections,
                              MarkUsageAdopted, MarkUsageExecuted,
                              ListSkillCandidates,
                              ObserveMemory, ObservePersonalHabit, ProcessLearningCase,
                              MemoryRelation, RecallExperiences, RecallMemory,
                              RecallMemoryRelations, RecallResult, RecallSkills,
                              ResolveLearningRefs,
                              SkillCandidate,
                              RecallGroupFacts,
                              VerifyUsage)
from memory.domain import MemoryScope


@runtime_checkable
class MemoryCommandPort(Protocol):
    async def observe(self, command: ObserveMemory) -> None: ...
    async def forget(self, command: ForgetMemory) -> None: ...


@runtime_checkable
class MemoryQueryPort(Protocol):
    async def recall(self, query: RecallMemory) -> RecallResult: ...


@runtime_checkable
class MemoryEventPort(Protocol):
    async def publish(self, event: MemoryEvent) -> None: ...


@runtime_checkable
class GroupKnowledgePort(Protocol):
    async def ingest_fact(self, command: IngestGroupFact) -> str: ...
    async def recall_facts(self, query: RecallGroupFacts) -> RecallResult: ...


@runtime_checkable
class MemoryRelationPort(Protocol):
    async def create(self, command: CreateMemoryRelation) -> str: ...
    async def recall(
        self, query: RecallMemoryRelations
    ) -> tuple[MemoryRelation, ...]: ...
    async def archive_before(self, scope: MemoryScope, before: int, limit: int = 1000) -> int: ...


@runtime_checkable
class BotFactObservationPort(Protocol):
    async def ingest(
        self, command: IngestBotFactObservations
    ) -> tuple[str, ...]: ...


@runtime_checkable
class BotReflectionPort(Protocol):
    async def ingest(
        self, command: IngestBotReflections
    ) -> tuple[str, ...]: ...


@runtime_checkable
class LearningPort(Protocol):
    async def process_case(self, command: ProcessLearningCase) -> str: ...
    async def assemble_case(self, command: AssembleCase) -> str | None: ...
    async def recall_experiences(self, command: RecallExperiences) -> tuple[str, list[str]]: ...
    async def complete_experience_usage(self, command: CompleteExperienceUsage) -> None: ...
    async def recall_skills(self, command: RecallSkills) -> tuple[str, list[str]]: ...
    async def resolve_learning_refs(self, command: ResolveLearningRefs) -> tuple[str, ...]: ...
    async def list_skill_candidates(self, command: ListSkillCandidates) -> tuple[SkillCandidate, ...]: ...
    async def approve_skill_candidate(self, command: ApproveSkillCandidate) -> bool: ...
    async def complete_skill_usage(self, command: CompleteSkillUsage) -> None: ...
    async def mark_usage_adopted(self, command: MarkUsageAdopted) -> int: ...
    async def mark_usage_executed(self, command: MarkUsageExecuted) -> int: ...
    async def verify_usage(self, command: VerifyUsage) -> int: ...


@runtime_checkable
class PersonalKnowledgePort(Protocol):
    async def create_record(self, command: CreatePersonalRecord) -> str: ...
    async def create_projection(self, command: CreatePersonalProjection) -> str: ...
    async def ingest(self, command: IngestPersonalKnowledge) -> str: ...
    async def observe_habit(self, command: ObservePersonalHabit) -> str: ...
    async def format_projected_context(self, command: FormatProjectedContext) -> str: ...
    async def rebuild(self, scope: MemoryScope) -> Mapping[str, Any]: ...
    async def export(self, scope: MemoryScope, *, cursor: str | None = None, limit: int = 1000) -> Mapping[str, Any]: ...
    async def get_record_impact(self, scope: MemoryScope, record_id: str) -> Mapping[str, Any]: ...
    async def delete(self, scope: MemoryScope) -> Mapping[str, Any]: ...
    async def delete_record(self, scope: MemoryScope, record_id: str) -> bool: ...
    async def revoke_projection(self, scope: MemoryScope, projection_id: str) -> bool: ...
